-- One story, told by many feeds.
--
-- A directory of this size carries the same announcement dozens of times, and a
-- topic river built out of that shows a reader one story twelve times over. The
-- key is a hash of the headline's significant words, computed when the item is
-- stored, so grouping later is a string comparison rather than a similarity
-- search over millions of rows.
--
-- Three states, and the difference between two of them is what lets the
-- backfill terminate:
--
--   a hash  -- group this item with anything carrying the same hash
--   ''      -- looked at, and deliberately never grouped: the title is too
--              short or too generic to be safe ("Weeknotes", "Links")
--   NULL    -- not yet examined; written before this column existed
--
-- Collapsing the middle case into NULL would leave every ungroupable row in the
-- worker's queue for good, and it would re-examine them on every pass forever.
--
-- Adding a nullable column with no default is O(1) in SQLite: it rewrites the
-- table header, not the rows. That is the only reason this file is safe to run
-- against a table with 1.4M rows in it.
alter table feed_items add column cluster_key text;

-- Deliberately no indexes on feed_items here, and this is the interesting part.
--
-- The first version of this migration created two: one on (published_at desc,
-- cluster_key) to cover the river, and a partial one on the un-keyed rows to
-- feed the backfill. Neither can be built. Over 1.4M rows the index build runs
-- past the libSQL client's timeout, the statement dies with "fetch failed", and
-- because a migration file is not transactional and is only recorded once every
-- statement in it has succeeded, the boot that attempted it left the column
-- applied and the file unrecorded — so the next boot re-ran the ALTER, hit
-- "duplicate column name", and the crawler stayed down until a human fixed it.
--
-- Neither index was load-bearing:
--
--   * The river filters on feed_id and orders by published_at, both already
--     indexed. It only *selects* cluster_key, and grouping happens in JS.
--   * The backfill walks the primary key with a cursor instead of searching for
--     null rows, which is why it no longer needs an index to find its work.
--
-- If they are ever wanted, they have to be built out of band against Turso
-- directly, not from a statement the poller runs at boot.
