-- Stop writing an article body for every item of every feed, for ever.
--
-- `feed_items.content_html` is **10 GB of a 14 GB database** -- 5.7 KB average
-- over 1.75M rows, sampled with `avg(length(content_html))`. It is stored on
-- every crawl of every feed and read by exactly one page.
--
-- The reason to stop is not the storage bill, and this is worth being precise
-- about because an earlier pass looked at this column, measured the wrong
-- thing, and left it alone. Per-write payload really is irrelevant here: a
-- 1.1 MB batch measured 606ms against this database while a 12 KB batch
-- measured 27.9s in the same session. Bytes do not decide how long a write
-- takes.
--
-- What they decide is how large the database is, and size is what makes write
-- *slots* scarce. This database routinely commits 150 rows in 200-600ms and
-- then stalls for 71-302 seconds, with the stalls uncorrelated to row count,
-- payload, FTS triggers or batch size -- every one of those was measured and
-- eliminated. What is left is the database itself: 14 GB with a 1.75M-row FTS
-- index, under continuous insert load. Taking 10 GB out of it is the largest
-- lever available that does not involve moving off Turso.
--
-- The body is not lost. `item_extracts` (0016) already fetches and caches an
-- article the first time somebody opens it, so the reader keeps working and
-- the publisher is asked once rather than once per view. At the time of writing
-- that table held 31,100 rows against 1.75M items: **1.8% of the directory is
-- what anyone has ever actually read**, and that is the fraction now stored.
--
-- Two things this deliberately does NOT do:
--
--   * It does not drop the column and it does not null the existing rows.
--     Nulling 1.75M rows is 1.75M row-writes against a database that currently
--     cannot accept an empty write transaction inside 300 seconds, and SQLite
--     does not return freed pages without a VACUUM, so the write would be paid
--     for and the reported size would not move. Reclaiming the existing 10 GB
--     needs a maintenance window; this stops the growth today.
--   * It does not backfill `content_chars`. Old rows still carry their body so
--     the length can be measured directly; new rows carry the count instead.
alter table feed_items add column content_chars integer;

-- Why a count outlives the body it measures.
--
-- `isEpisode()` in apps/web/src/lib/media.js decides whether a post with audio
-- is *an episode* or *an article that happens to have audio*, and it decides by
-- measuring the body: under 1,200 characters of text and it is an episode.
-- With the body gone that measurement returns 0 for everything and every
-- podcast-shaped post in the directory silently reclassifies.
--
-- So the one thing ever asked of those 5.7 KB is kept: their length, tags
-- already stripped, as an integer. Four bytes instead of 5,746, and the
-- classification is bit-for-bit what it was.
